package com.demo.springcloud.batch.entity;

import lombok.Data;
import lombok.ToString;

import java.util.Date;

/**
 * @Author: ASUS
 * @description: TODO
 * @Date: 14:21 2020/7/5
 */
@Data
@ToString
public class EmployeesProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.emp_no
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private Integer empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.birth_date
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.first_name
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.gender
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_date
     *
     * @mbg.generated Sun Jul 05 13:32:59 CST 2020
     */
    private Date hireDate;

    private Integer sex;

    private String phone;
}
